### ISSUE TITLE
Merging pekko-http-cors into upstream pekko-http?

### ISSUE THREAD

**Issue by mdedetrich** [lomigmegard/pekko-http-cors#33]
As we have been working and doing changes to Pekko and its modules, we realized that pekko-http-cors creates a circular transitive dependency. That is, pekko-grpc depends on pekko-http-cors and pekko-http-cors depends on pekko-http and pekko-grpc depends on pekko-http.

This is causing interesting issues, basically there is always the risk where if we do an change that is internal to Pekko that shouldn't effect any external dependency we may end up having to do a change in pekko-http-cors. While this wasn't an issue with Akka because of its ultra stable API, as you may have noticed with us pinging you here to make new releases we are trying to do changes to Pekko to make it better for users in the long run before making an initial release.

The more salient point however is that pekko-http-cors implements what is a [W3C standard](https://www.w3.org/TR/2020/SPSD-cors-20200602/) and hence the natural place for such a thing is within Pekko-http. In fact I was quite surprised that this was an external library, to me any http server/client should have CORS as part of its core.

For the reasons stated above how do you feel about merging pekko-http-cors into upstream pekko-http, the best time to do so is now (i.e. before an initial release)? If you don't comfortable in doing this then don't hesitate in saying so, nothing will change with the current status quo. It also goes without saying that if the merge happens, any changes submitted to work/maintain the cors part of pekko-http will be greatly appreciated (in fact this goes for any changes to Pekko, not just one portion of the code). Although I personally have no qualms making you maintainer (which in ASF terms is a committer), because of ASF policy we can only do this once you have made contributions to the community and are voted to be accepted.

@lomigmegard wdyt?

**Comment by lomigmegard** [comment]
Hi @mdedetrich, 

The initial library was developed next to `akka-http` first, and after discussion with the maintainers, it wasn't deemed necessary to merge it. See [this issue and the associated threads](https://github.com/akka/akka-http/issues/118) in Google groups (from 2016!). 

The dependency graph you describe doesn't have a circular dependency, but indeed exhibits a "diamond" shape. I am not 100% sure to get which parts you are afraid might break between releases, but I fully trust your expertise here, and anyways such dependency pattern creates friction during releases for sure. 

I am neutral on the actual strategy, however if you think it will help the Pekko project I am happy to merge this library into `pekko-http`. I just saw you released a first RC1, what would be the timeline to do this merge? I don't expect it to take that long, but the configuration and documentation are always harder than anticipated :) 

Also side note, although this lib follows the W3C standard, there are quite a few unspecified cases in there, and the most opinionated decision was actually to chose the default values for the configuration. Thus while I agree it makes sense to have it built-in, it's not all straightforward and most implementation behave slightly differently on edge cases.

**Comment by mdedetrich** [comment]
Hi @lomigmegard 

> The initial library was developed next to akka-http first, and after discussion with the maintainers, it wasn't deemed necessary to merge it. See https://github.com/akka/akka-http/issues/118 in Google groups (from 2016!).

Thanks for the background context. This is quite some time ago, I just checked the git log of akka-grpc and it didn't even exist at this time (first commit was 2018) so the diamond dependency you talk about wouldn't have even been a concern then.

> The dependency graph you describe doesn't have a circular dependency, but indeed exhibits a "diamond" shape. I am not 100% sure to get which parts you are afraid might break between releases, but I fully trust your expertise here, and anyways such dependency pattern creates friction during releases for sure.

Indeed the friction part is the part I am most concerned about. 

> I am neutral on the actual strategy, however if you think it will help the Pekko project I am happy to merge this library into pekko-http. I just saw you released a first RC1, what would be the timeline to do this merge? I don't expect it to take that long, but the configuration and documentation are always harder than anticipated :)

So you are correct that we are commencing with RC1 however this is just for pekko, not pekko and all of its modules (including pekko-http) so there is definitely time (and its already been discussed with the community that if you agree with this then we are happy to proceed now). In regards to the actual work, I was thinking of setting up the PR in a week (about to go on holidays) and giving you authorship via `Co-Authoered-By` but if you want to go ahead and create a PR then go ahead! The immediate technical question is what artifact/sbt sub project it should go under but I think that `http-cors` (akin to `http-caching` which already exists) is not going to cause any controversy, similarly the package `org.apache.pekko.cors` is appropriate.

> Also side note, although this lib follows the W3C standard, there are quite a few unspecified cases in there, and the most opinionated decision was actually to chose the default values for the configuration. Thus while I agree it makes sense to have it built-in, it's not all straightforward and most implementation behave slightly differently on edge cases.

If this is documented then it should be a non issue

On a final note if you are going to go ahead with this decision it would be great if you are able to sign a SGA (software grant agreement) to the ASF. This is documented at https://www.apache.org/licenses/contributor-agreements.html#grants and the form is at https://www.apache.org/licenses/software-grant-template.pdf .

If you have any other questions then feel free to let me know.

**Comment by lomigmegard** [comment]
Hey @mdedetrich 

>  I was thinking of setting up the PR in a week (about to go on holidays) and giving you authorship via Co-Authoered-By

That sounds perfect to me. Please ping me in the PR if you have questions regarding specific points, I will try to give context where I can. 

>  The immediate technical question is what artifact/sbt sub project it should go under but I think that http-cors (akin to http-caching which already exists) is not going to cause any controversy, similarly the package org.apache.pekko.cors is appropriate.

Yes I agree. 

> On a final note if you are going to go ahead with this decision it would be great if you are able to sign a SGA (software grant agreement) to the ASF. 

Sure, I will do that today, granting the pekko-http-cors source code to the ASF. Do I also have to sign the ICLA (Individual Contributor License Agreement)?

**Comment by mdedetrich** [comment]
> Sure, I will do that today, granting the pekko-http-cors source code to the ASF. Do I also have to sign the ICLA (Individual Contributor License Agreement)?

Checking on it now

**Comment by lomigmegard** [comment]
Anyways it doesn't hurt to setup my Apache Id if I want to further contribute in pekko, I will proceed with both. Thanks Matthew

**Comment by pjfanning** [comment]
@lomigmegard it seems we now have your SGA and iCLA on record within the ASF.

It might be nice to get the pekko-http-cors added to apache/incubator-pekko-http repo using a PR from you so that your name appears on the commit.

If you have time to do such a PR
* could you add the code to a 'http-cors' folder off the root folder (similar to what you in this repo but with the 'pekko' removed?
* the benchmark could go to 'http-cors-bench-jmh' 
* the example might be better placed in the https://github.com/apache/incubator-pekko-samples project
* package could be `org.apache.pekko.http.cors`
* we'll need Apache headers on the files
https://github.com/apache/incubator-pekko-http/blob/main/http-core/src/main/scala/org/apache/pekko/http/ParsingErrorHandler.scala#L1-L8
* apache/incubator-pekko-http uses sbt-header plugin and `sbt +headerCreate` will add this header to all the files it is missing from
* if you don't like the text of that header, we could use the standard Apache header
https://github.com/apache/spark/blob/master/common/utils/src/main/scala/org/apache/spark/SparkException.scala#L1-L16
* our conf files have a different header
https://github.com/apache/incubator-pekko-http/blob/main/http-core/src/main/resources/reference.conf#L1

The docs and the wiring the build together - these can be done as a separate PR and someone else could look at those if you are busy.

**Comment by mdedetrich** [comment]
> It might be nice to get the pekko-http-cors added to apache/incubator-pekko-http repo using a PR from you so that your name appears on the commit.

It's not necessary to be the physical author to set the author name to something else. The author name is just a free form text field that you can set to anything you want, (I did the same technique with the formatting commits).

There is also `Co-Authored-By` which has been used various times.

Anyways I will be free to start working on this in a couple of days, if @lomigmegard wants to work on it himself that's fine just ping this issue so we don't double work.

**Comment by lomigmegard** [comment]
Thanks @mdedetrich , I will let you do the initial move then. You will be quicker to do the sbt setup inside pekko-http. 

But I am of course available to reply or help on the PR if needed.

> There is also Co-Authored-By which has been used various times.

I would appreciate the (co)authored, at least on the initial commit. Thanks, if you do it on your side then please use `Lomig Mégard <dev@lomig.ch>`

**Comment by mdedetrich** [comment]
@lomigmegard PR created at https://github.com/apache/incubator-pekko-http/pull/208

**Comment by lomigmegard** [comment]
This [comment](https://github.com/apache/incubator-pekko-http/pull/208#discussion_r1246788512) from @pjfanning made me wonder what is actually the status of the original `akka-http-cors` project? Since `pekko-http-cors` was a fork, and the grant only mentioned it, I imagine the original repository isn't impacted. However the code is _very_ close and the legal aspects of it are beyond my knowledge. 

The original `akka-http-cors` project is still useful for the akka users (~300k downloads per month!), and would be good to stay alive (as it as been for the last years, in maintenance-only mode).

**Comment by mdedetrich** [comment]
Obligatory IANAL comments follow

> This [comment](https://github.com/apache/incubator-pekko-http/pull/208#discussion_r1246788512) from @pjfanning made me wonder what is actually the status of the original `akka-http-cors` project? Since `pekko-http-cors` was a fork, and the grant only mentioned it, I imagine the original repository isn't impacted. However the code is _very_ close and the legal aspects of it are beyond my knowledge.

I don't think there are any legal implications here. You wrote the akka-http-cors code yourself (its not associated in any way to Lightbend since you are not employed there and you also didn't contribute it to the repo) and you also wrote pekko-http-cors yourself (which is based off akka-http-cors)
 
> The original `akka-http-cors` project is still useful for the akka users (~300k downloads per month!), and would be good to stay alive (as it as been for the last years, in maintenance-only mode).

Given what I said previously, what you do with akka-http-cors is completely up to you.

**Comment by pjfanning** [comment]
@lomigmegard nothing about the Software Grant to the ASF prevents you from maintaining your own projects - akka-http-cors or pekko-http-core. It just gives the Apache Pekko project permission to include your code in the Apache Pekko repos and to distribute a pekko-http-jars jar of our own.

**Comment by lomigmegard** [comment]
@pjfanning @mdedetrich thanks for confirming 👍

**Comment by mdedetrich** [comment]
@lomigmegard With https://github.com/apache/incubator-pekko-http/pull/208 merged I think its okay to close this ticket and archive the repo?

On another note I want to make an announcement on Apache Pekko's official twitter handle announcing that akka-http-cors is now official part of pekko-http and will be available in the first release, do you have any issues with this (and with being tagged in the twitter post?)

**Comment by lomigmegard** [comment]
> I think its okay to close this ticket and archive the repo?

Yes, thanks. I will do the cleanup and archiving in the coming days.

> do you have any issues with this (and with being tagged in the twitter post?)

not at all, please do :)
